# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('d_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('d_cityc', models.CharField(max_length=10)),
                ('d_name', models.CharField(max_length=50)),
                ('d_fone', models.IntegerField()),
                ('d_email', models.EmailField(max_length=50)),
                ('d_active', models.CharField(max_length=8)),
                ('d_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('r_fone', models.IntegerField()),
                ('r_email', models.EmailField(max_length=50)),
                ('r_active', models.CharField(max_length=8)),
                ('r_rut', models.IntegerField()),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winn.Conductor')),
            ],
        ),
    ]
