# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winn', '0002_auto_20170124_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciudad', models.CharField(max_length=10)),
                ('NoCarreras', models.IntegerField()),
                ('Plazo', models.IntegerField()),
                ('Modalidad', models.CharField(max_length=20)),
                ('Premio', models.IntegerField()),
                ('PeriodoCarga', models.CharField(max_length=50)),
            ],
        ),
    ]
