# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winn', '0003_condiciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condiciones',
            old_name='NoCarreras',
            new_name='NumCarreras',
        ),
    ]
