# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winn', '0004_auto_20170127_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciudad', models.CharField(max_length=10)),
                ('NumCarreras', models.IntegerField()),
                ('Plazo', models.IntegerField()),
                ('Modalidad', models.CharField(max_length=20)),
                ('Premio', models.IntegerField()),
                ('PeriodoCarga', models.CharField(max_length=50)),
            ],
        ),
    ]
