# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winn', '0006_auto_20170130_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesref',
            name='PeriodoCarga',
            field=models.CharField(max_length=80),
        ),
    ]
