# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winn', '0007_auto_20170130_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoBienvenida',
            fields=[
                ('driver_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_emitido', models.DateField()),
                ('monto_pago', models.IntegerField()),
            ],
        ),
    ]
