# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winn', '0008_historicobienvenida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicobienvenida',
            old_name='fecha_emitido',
            new_name='date',
        ),
    ]
