# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichero_dim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fichero', models.FileField(upload_to='ficheros')),
            ],
        ),
    ]
